#!/bin/python3

import sys


n = int(input().strip())
a = []
for a_i in range(n):
    a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
    a.append(a_t)


sum1 = 0
sum2 = 0

for i in range(0, n):
    sum1 += a[i][i]

p = n-1
for i in range(0, n):
    sum2 += a[i][p]
    p -= 1




if(sum1 > sum2):
    print(sum1-sum2)
else:
    print(sum2 - sum1)
    
